name: Deploy

on:
  - repository_dispatch
  - push
  - pull_request
  - pull_request_review

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment variables
        shell: bash
        run: |
          echo ::set-env name=BRANCH::$(echo "${GITHUB_REF##*/}")
          echo ::set-env name=RELEASE_BRANCH::$(echo "master")
          echo ::set-env name=PUBLISH_DIR::$(echo "public")
          echo ::set-env name=REPOSITORY_NAME::$(echo ${GITHUB_REPOSITORY} | awk -F / '{print $2}')
      - name: Set deploy domain
        run: |
          DOMAIN_BASE="${REPOSITORY_NAME}.jas.bio"
          if [ $BRANCH == "master" ];then
            DOMAIN="${DOMAIN_BASE}"
          elif [ $GITHUB_EVENT_NAME == "pull_request" ];then
            DOMAIN="pr-${{ github.event.number }}.${DOMAIN_BASE}"
          else
            DOMAIN="${BRANCH}.${DOMAIN_BASE}"
          fi
          echo "http://$DOMAIN"
          echo ::set-env name=DOMAIN::$(echo "$DOMAIN")
      - uses: actions/checkout@v2
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Pull packages
        run: yarn
      - name: Build site
        run: yarn build
      - name: Deploying to http://${{env.DOMAIN}}
        run: yarn surge ${PUBLISH_DIR} ${DOMAIN}
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
      - name: Comment link on PR
        if: github.event_name == 'pull_request'
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Deployed commit ${{ github.sha }} at http://${{env.DOMAIN}}"
