name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${BRANCH_NAME}.${{ secrets.DOMAIN_NAME }}.jas.bio"
#       - uses: actions/checkout@v2
#       - uses: nelonoel/branch-name@v1
#       - name: Get yarn cache
#         id: yarn-cache
#         run: echo "::set-output name=dir::$(yarn cache dir)"
#       - uses: actions/cache@v1
#         with:
#           path: ${{ steps.yarn-cache.outputs.dir }}
#           key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-yarn-
#       - name: Pull packages
#         run: yarn
#       - name: Build site
#         run: yarn build
#       - name: Deploy to surge
#         uses: dswistowski/surge-sh-action@v1
#         with:
#           domain: "${BRANCH_NAME}.${{ secrets.DOMAIN_NAME }}.jas.bio"
#           project: "public"
#           login: ${{ secrets.surge_login }}
#           token: ${{ secrets.surge_token }}
#       - name: Deploy
#         if: ${BRANCH_NAME} == "master"
#         uses: crazy-max/ghaction-github-pages@v1
#         with:
#           target_branch: gh-pages
#           build_dir: public
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
