name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #     - uses: actions/cache@v1
      #       with:
      #         path: ${{ steps.yarn-cache.outputs.dir }}
      #         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #         restore-keys: |
      #           ${{ runner.os }}-yarn-
      - name: Pull packages
        run: yarn
      - name: Build site
        run: yarn build
      - name: Deploy to surge
      - uses: dswistowski/surge-sh-action@v1
        with:
          domain: "jc-ga.surge.sh"
          project: "public"
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
